services:
  owncloud_sync:
    build: .
    container_name: owncloud-client-cmd
    env_file:
      - .env 
    environment:
      - OWNCLOUD_URL=${OWNCLOUD_URL}   
      - OWNCLOUD_USERNAME=${OWNCLOUD_USERNAME}
      - OWNCLOUD_PASSWORD=${OWNCLOUD_PASSWORD}
      - LOCAL_SYNC_DIR=${LOCAL_SYNC_DIR}
      - REMOTE_SYNC_DIR=${REMOTE_SYNC_DIR}
      - SYNC_INTERVAL=${SYNC_INTERVAL}
      - OWNCLOUD_EXCLUDE=${OWNCLOUD_EXCLUDE}
    volumes:
      - ./sync:${LOCAL_SYNC_DIR}
    network_mode: host