name: docker-image-ci
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: login-to-docker-hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: get-latest-release-tag
      id: get_release
      run: |
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/rustedchip/owncloud-client-cmd/releases/latest | jq -r .tag_name)
        echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

    - name: build-the-docker-image
      run: |
        TIMESTAMP=$(date +%s)
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV  # Save timestamp to environment variable
        docker build -t rustedchip/owncloud-client-cmd:latest -t rustedchip/owncloud-client-cmd:$LATEST_RELEASE -t rustedchip/owncloud-client-cmd:$TIMESTAMP .

    - name: push-to-docker-hub
      run: |
        docker push rustedchip/owncloud-client-cmd:latest
        docker push rustedchip/owncloud-client-cmd:$TIMESTAMP
        docker push rustedchip/owncloud-client-cmd:$LATEST_RELEASE

    - name: log-out-from-docker-hub
      run: docker logout
